### ISSUE TITLE
Incapable of using imagemin on png

### ISSUE THREAD

**Issue by JnMik** [imagemin/optipng-bin#62] opened 2015-11-09 19:52 UTC
node : v4.2.2
npm : 3.3.12
optipng-bin : 3.0.2

Running from latest grunt-contrib-imagemin
Get this error on imagemin.run

Warning: Error: spawn -some-project-root-/node_modules/optipng-bin/vendor/optipng ENOENT in file -some-project-root-/images/address.png Use --force to continue.

**Comment by JnMik** [comment] 2015-11-09 19:59
Hmm with 3.0.2, it was failing at the first image in the folder (address.png), with 3.0.1, it process few images before ending up with Warning: Error: spawn again, but address.png doesn't trigger any errors.

**Comment by shinnn** [comment] 2015-11-09 20:01
Can you create a small repository by which we can reproduce the problem?

**Comment by JnMik** [comment] 2015-11-09 22:35
Yeah maybe I'll have time tomorrow for that.
You can also check my last 2 to comments here : 
https://github.com/gruntjs/grunt-contrib-imagemin/issues/321#issuecomment-155203582

It gives a good idea

**Comment by jcampalo** [comment] 2015-11-30 11:32
I get a previous error when it's installing all dependencies from npm, after this I get exactly the same error as commented above.

> optipng-bin@3.0.3 postinstall /home/appversebank/bamboo-agent-home/xml-data/build-dir/AB-DM3-JOB1/Web/WebResources/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
build	30-Nov-2015 11:45:04	> node lib/install.js
build	30-Nov-2015 11:45:04	
error	30-Nov-2015 11:45:08	  ⚠ Response code 503 (Service Unavailable)
error	30-Nov-2015 11:45:08	  ⚠ optipng pre-build test failed
error	30-Nov-2015 11:45:08	  ℹ compiling from source
error	30-Nov-2015 11:45:13	  ✖ Error: ./configure --with-system-zlib --prefix="/home/appversebank/bamboo-agent-home/xml-data/build-dir/AB-DM3-JOB1/Web/WebResources/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/home/appversebank/bamboo-agent-home/xml-data/build-dir/AB-DM3-JOB1/Web/WebResources/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
error	30-Nov-2015 11:45:13	Command failed: /bin/sh -c ./configure --with-system-zlib --prefix="/home/appversebank/bamboo-agent-home/xml-data/build-dir/AB-DM3-JOB1/Web/WebResources/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/home/appversebank/bamboo-agent-home/xml-data/build-dir/AB-DM3-JOB1/Web/WebResources/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor"
error	30-Nov-2015 11:45:13	
error	30-Nov-2015 11:45:13	    at ChildProcess.exithandler (child_process.js:751:12)
error	30-Nov-2015 11:45:13	    at ChildProcess.emit (events.js:110:17)
error	30-Nov-2015 11:45:13	    at maybeClose (child_process.js:1015:16)
error	30-Nov-2015 11:45:13	    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I don't know if it has some relation to this issue.

**Comment by shinnn** [comment] 2015-11-30 12:15
The solution described in https://github.com/imagemin/imagemin/issues/133#issuecomment-152750841  will fix [the original issue](https://github.com/imagemin/optipng-bin/issues/62#issue-115952022).

@jcampalo Seems like a duplicate of https://github.com/imagemin/imagemin/issues/139.

**Closed by shinnn** 2015-11-30 12:15 UTC
